# DSCI FINAL
## 組員
- 111590004
- 111590011
- 111590028
- 111590042

In [14]:
## 將 109 年 ~ 113 年檔案讀入並過濾不必要資料後合併
import pandas as pd

# List to hold individual dataframes
df_list = []

# Loop through years 109 to 113
for year in range(109, 114):
    filename = f'/content/{year}_大專校院科系別概況.csv'
    try:
        # Read the CSV file
        df = pd.read_csv(filename)

        # Drop specified columns, including '學年度' and '教師數'
        columns_to_drop = ['上學年度畢業生數', '縣市名稱', '體系別', '學年度', '教師數']
        df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

        # Add '年份' column
        df['年份'] = year

        df_list.append(df)
        print(f"Successfully processed {filename}")
    except FileNotFoundError:
        print(f"Warning: File not found for year {year} at {filename}. Skipping.")
    except Exception as e:
        print(f"Error processing {filename}: {e}. Skipping.")

# Concatenate all dataframes into a single one
if df_list:
    combined_df = pd.concat(df_list, ignore_index=True)
    print("\nCombined DataFrame created. Displaying the first 5 rows:")
    display(combined_df.head())
    print("\nCombined DataFrame info:")
    combined_df.info()

    # Save the combined DataFrame to a CSV file
    output_filename = '/content/combined_university_data.csv'
    combined_df.to_csv(output_filename, index=False)
    print(f"\nCombined data saved to {output_filename}")
else:
    print("No dataframes were processed successfully.")

Successfully processed /content/109_大專校院科系別概況.csv
Successfully processed /content/110_大專校院科系別概況.csv
Successfully processed /content/111_大專校院科系別概況.csv
Successfully processed /content/112_大專校院科系別概況.csv
Successfully processed /content/113_大專校院科系別概況.csv

Combined DataFrame created. Displaying the first 5 rows:

   學校代碼    學校名稱      科系代碼        科系名稱 日間∕進修別   等級別  學生數   年份
0     1  國立政治大學  01111001        教育學系    D 日  D 博士  113  109
1     1  國立政治大學  01111001        教育學系    D 日  M 碩士   28  109
2     1  國立政治大學  01111001        教育學系    D 日  B 學士  225  109
3     1  國立政治大學  01114005  教育行政與政策研究所    D 日  M 碩士   45  109
4     1  國立政治大學  01114006  學校行政碩士在職專班    N 職  M 碩士   80  109

Combined DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48710 entries, 0 to 48709
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學校代碼    48710 non-null  int64
 1   學校名稱    48710 non-null  object
 2   科系代碼    48710 non-null  object
 3   科系名稱    48710 non-null  object
 4   日間∕進修別  48710 non-null  object
 5   等級別     46385 non-null  object
 6   學生數     48710 non-null  object
 7   年份      48710 non-null  int64
dtypes: int64(2), object(6)
memory usage: 3.0+ MB

Combined data saved to /content/combined_university_data.csv

In [15]:
import pandas as pd

# Load the combined data if not already loaded (for standalone execution)
try:
    if 'combined_df' not in locals() or combined_df.empty:
        combined_df = pd.read_csv('/content/combined_university_data.csv')
except FileNotFoundError:
    print("Error: 'combined_university_data.csv' not found. Please ensure the previous cell was executed successfully.")
    exit()

# Check for null values in the '等級別' column
null_count_等級別 = combined_df['等級別'].isnull().sum()
total_rows = len(combined_df)

print(f"Total rows in the DataFrame: {total_rows}")
print(f"Number of null values in '等級別' column: {null_count_等級別}")
print(f"Number of non-null values in '等級別' column: {total_rows - null_count_等級別}")

print("\nValue counts for '等級別' column (including NaN):")
display(combined_df['等級別'].value_counts(dropna=False))

Total rows in the DataFrame: 48710
Number of null values in '等級別' column: 2325
Number of non-null values in '等級別' column: 46385

Value counts for '等級別' column (including NaN):

等級別
M 碩士     18005
B 學士      9818
B 四技      8699
D 博士      4995
C 二技      2647
NaN       2325
5 五專      1251
2 二專       929
X 4+X       24
5 七年        12
C 二年制        5
Name: count, dtype: int64

In [16]:
import numpy as np

# Define the list of valid '等級別' categories
valid_categories = ['M 碩士', 'B 學士', 'D 博士']

# Filter the DataFrame to keep only rows with valid '等級別' categories
# Also explicitly include NaN values in the filter to be removed (as they are not in valid_categories)
filtered_df = combined_df[combined_df['等級別'].isin(valid_categories)]

print(f"Original number of rows: {len(combined_df)}")
print(f"Number of rows after filtering '等級別': {len(filtered_df)}")

print("\nFiltered DataFrame head:")
display(filtered_df.head())

print("\nFiltered DataFrame info:")
filtered_df.info()

print("\nValue counts for '等級別' in the filtered DataFrame:")
display(filtered_df['等級別'].value_counts(dropna=False))

Original number of rows: 48710
Number of rows after filtering '等級別': 32818

Filtered DataFrame head:

   學校代碼    學校名稱      科系代碼        科系名稱 日間∕進修別   等級別  學生數   年份
0     1  國立政治大學  01111001        教育學系    D 日  D 博士  113  109
1     1  國立政治大學  01111001        教育學系    D 日  M 碩士   28  109
2     1  國立政治大學  01111001        教育學系    D 日  B 學士  225  109
3     1  國立政治大學  01114005  教育行政與政策研究所    D 日  M 碩士   45  109
4     1  國立政治大學  01114006  學校行政碩士在職專班    N 職  M 碩士   80  109

Filtered DataFrame info:
<class 'pandas.core.frame.DataFrame'>
Index: 32818 entries, 0 to 48706
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學校代碼    32818 non-null  int64
 1   學校名稱    32818 non-null  object
 2   科系代碼    32818 non-null  object
 3   科系名稱    32818 non-null  object
 4   日間∕進修別  32818 non-null  object
 5   等級別     32818 non-null  object
 6   學生數     32818 non-null  object
 7   年份      32818 non-null  int64
dtypes: int64(2), object(6)
memory usage: 2.3+ MB

Value counts for '等級別' in the filtered DataFrame:

等級別
M 碩士    18005
B 學士     9818
D 博士     4995
Name: count, dtype: int64

### 將篩選後的資料拆分為碩士、學士、博士三個資料框
現在，我們將 `filtered_df` 根據 '等級別' 欄位拆分為三個獨立的資料框：碩士、學士和博士。

In [17]:
import pandas as pd

# 確保 filtered_df 可用 (它應該來自之前的單元格)
# 如果此單元格單獨運行，請取消註釋以下行以確保 df 存在：
# combined_df = pd.read_csv('/content/combined_university_data.csv')
# valid_categories = ['M 碩士', 'B 學士', 'D 博士']
# filtered_df = combined_df[combined_df['等級別'].isin(valid_categories)]

# 創建碩士學位資料框
master_university_df = filtered_df[filtered_df['等級別'] == 'M 碩士'].copy()
print("\n碩士大學資料框 head:")
display(master_university_df.head())
print("\n碩士大學資料框 info:")
master_university_df.info()

# 創建學士學位資料框
bachelor_university_df = filtered_df[filtered_df['等級別'] == 'B 學士'].copy()
print("\n學士大學資料框 head:")
display(bachelor_university_df.head())
print("\n學士大學資料框 info:")
bachelor_university_df.info()

# 創建博士學位資料框
doctorate_university_df = filtered_df[filtered_df['等級別'] == 'D 博士'].copy()
print("\n博士大學資料框 head:")
display(doctorate_university_df.head())
print("\n博士大學資料框 info:")
doctorate_university_df.info()

碩士大學資料框 head:

   學校代碼    學校名稱      科系代碼        科系名稱 日間∕進修別   等級別 學生數   年份
1     1  國立政治大學  01111001        教育學系    D 日  M 碩士  28  109
3     1  國立政治大學  01114005  教育行政與政策研究所    D 日  M 碩士  45  109
4     1  國立政治大學  01114006  學校行政碩士在職專班    N 職  M 碩士  80  109
5     1  國立政治大學  01121004     幼兒教育研究所    D 日  M 碩士  39  109
8     1  國立政治大學  02211019       宗教研究所    D 日  M 碩士  31  109

碩士大學資料框 info:
<class 'pandas.core.frame.DataFrame'>
Index: 18005 entries, 1 to 48705
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學校代碼    18005 non-null  int64
 1   學校名稱    18005 non-null  object
 2   科系代碼    18005 non-null  object
 3   科系名稱    18005 non-null  object
 4   日間∕進修別  18005 non-null  object
 5   等級別     18005 non-null  object
 6   學生數     18005 non-null  object
 7   年份      18005 non-null  int64
dtypes: int64(2), object(6)
memory usage: 1.2+ MB

學士大學資料框 head:

    學校代碼    學校名稱      科系代碼    科系名稱 日間∕進修別   等級別  學生數   年份
2      1  國立政治大學  01111001    教育學系    D 日  B 學士  225  109
11     1  國立政治大學  02221020    歷史學系    D 日  B 學士  160  109
16     1  國立政治大學  02222031    民族學系    D 日  B 學士  178  109
19     1  國立政治大學  02231022     哲學系    D 日  B 學士  179  109
22     1  國立政治大學  02311009  英國語文學系    D 日  B 學士  292  109

學士大學資料框 info:
<class 'pandas.core.frame.DataFrame'>
Index: 9818 entries, 2 to 48706
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學校代碼    9818 non-null   int64
 1   學校名稱    9818 non-null   object
 2   科系代碼    9818 non-null   object
 3   科系名稱    9818 non-null   object
 4   日間∕進修別  9818 non-null   object
 5   等級別     9818 non-null   object
 6   學生數     9818 non-null   object
 7   年份      9818 non-null   int64
dtypes: int64(2), object(6)
memory usage: 690.3+ KB

博士大學資料框 head:

    學校代碼    學校名稱      科系代碼    科系名稱 日間∕進修別   等級別  學生數   年份
0      1  國立政治大學  01111001    教育學系    D 日  D 博士  113  109
7      1  國立政治大學  02211019   宗教研究所    D 日  D 博士   27  109
9      1  國立政治大學  02221020    歷史學系    D 日  D 博士   26  109
12     1  國立政治大學  02221021  台灣史研究所    D 日  D 博士   19  109
14     1  國立政治大學  02222031    民族學系    D 日  D 博士   15  109

博士大學資料框 info:
<class 'pandas.core.frame.DataFrame'>
Index: 4995 entries, 0 to 48693
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   學校代碼    4995 non-null   int64
 1   學校名稱    4995 non-null   object
 2   科系代碼    4995 non-null   object
 3   科系名稱    4995 non-null   object
 4   日間∕進修別  4995 non-null   object
 5   等級別     4995 non-null   object
 6   學生數     4995 non-null   object
 7   年份      4995 non-null   int64
dtypes: int64(2), object(6)
memory usage: 351.2+ KB

### 儲存拆分後的大學資料框為 CSV 檔案
現在，我們將這三個獨立的資料框儲存為各自的 CSV 檔案。

In [18]:
# 儲存為 CSV 檔案
master_university_df.to_csv('/content/大學資料_碩士.csv', index=False)
bachelor_university_df.to_csv('/content/大學資料_學士.csv', index=False)
doctorate_university_df.to_csv('/content/大學資料_博士.csv', index=False)

print("大學資料框已儲存為：")
print("- /content/大學資料_碩士.csv")
print("- /content/大學資料_學士.csv")
print("- /content/大學資料_博士.csv")

大學資料框已儲存為：
- /content/大學資料_碩士.csv
- /content/大學資料_學士.csv
- /content/大學資料_博士.csv

In [19]:
import pandas as pd

# Load the 學門查詢.csv data
subject_df = pd.read_csv('/content/學門查詢.csv')

print("Original 學門查詢 DataFrame head:")
display(subject_df.head())

print("Original 學門查詢 DataFrame info:")
subject_df.info()

# Drop specified columns
columns_to_drop_subject = ['領域簡介', '學門簡介', '學類簡介', '細學類簡介']
subject_df = subject_df.drop(columns=[col for col in columns_to_drop_subject if col in subject_df.columns])

print("\nProcessed 學門查詢 DataFrame head (after dropping columns):")
display(subject_df.head())

print("\nProcessed 學門查詢 DataFrame info:")
subject_df.info()

Original 學門查詢 DataFrame head:

,領域代碼/名稱,領域簡介,學門代碼/名稱,學門簡介,學類代碼/名稱,學類簡介,細學類代碼/名稱,細學類簡介
0,01 教育領域,屬於該領域之學類教導學生學習和教學有關的理論、方法、實務及相關的研究、行政和支援服務。,011 教育學門,包括教育學、學前教育、普通科目學科教學、專業科目學科教學等學類。,0111 教育學學類,學習將知識和能力傳授給他人的理論、方法和技能。相關課程及資格包含：教育哲學、教育史、教育心理...,01111 綜合教育細學類,培育綜合性的教育人才，發展整合性的教育學術，如教育學、初等教育、中等教育、高等教育、國民教育...
1,01 教育領域,屬於該領域之學類教導學生學習和教學有關的理論、方法、實務及相關的研究、行政和支援服務。,011 教育學門,包括教育學、學前教育、普通科目學科教學、專業科目學科教學等學類。,0111 教育學學類,學習將知識和能力傳授給他人的理論、方法和技能。相關課程及資格包含：教育哲學、教育史、教育心理...,01112 成人教育細學類,培育成人與繼續教育、高齡者教育、終身教育之教學與研究人才，使學生具備從事成人教育之學術研究、...
2,01 教育領域,屬於該領域之學類教導學生學習和教學有關的理論、方法、實務及相關的研究、行政和支援服務。,011 教育學門,包括教育學、學前教育、普通科目學科教學、專業科目學科教學等學類。,0111 教育學學類,學習將知識和能力傳授給他人的理論、方法和技能。相關課程及資格包含：教育哲學、教育史、教育心理...,01113 特殊教育細學類,培育特殊教育學術研究與教學之人才，提供進修機會與地區性特殊教育推廣與輔導工作，達成零拒絕與融...
3,01 教育領域,屬於該領域之學類教導學生學習和教學有關的理論、方法、實務及相關的研究、行政和支援服務。,011 教育學門,包括教育學、學前教育、普通科目學科教學、專業科目學科教學等學類。,0111 教育學學類,學習將知識和能力傳授給他人的理論、方法和技能。相關課程及資格包含：教育哲學、教育史、教育心理...,01114 教育行政細學類,培育從事各類教育和學校行政、政策、領導的教學和學術研究之人才，提供各級各類教育行政及學校行政...
4,01 教育領域,屬於該領域之學類教導學生學習和教學有關的理論、方法、實務及相關的研究、行政和支援服務。,011 教育學門,包括教育學、學前教育、普通科目學科教學、專業科目學科教學等學類。,0111 教育學學類,學習將知識和能力傳授給他人的理論、方法和技能。相關課程及資格包含：教育哲學、教育史、教育心理...,01115 課程與教學細學類,培育課程與教學學術領域的教學和研究人才，使學生具備課程與教學的理論基礎、設計、實施、評鑑和改...

Original 學門查詢 DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   領域代碼/名稱   174 non-null    object
 1   領域簡介      174 non-null    object
 2   學門代碼/名稱   174 non-null    object
 3   學門簡介      174 non-null    object
 4   學類代碼/名稱   174 non-null    object
 5   學類簡介      174 non-null    object
 6   細學類代碼/名稱  174 non-null    object
 7   細學類簡介     174 non-null    object
dtypes: object(8)
memory usage: 11.0+ KB

Processed 學門查詢 DataFrame head (after dropping columns):

   領域代碼/名稱   學門代碼/名稱     學類代碼/名稱        細學類代碼/名稱
0  01 教育領域  011 教育學門  0111 教育學學類   01111 綜合教育細學類
1  01 教育領域  011 教育學門  0111 教育學學類   01112 成人教育細學類
2  01 教育領域  011 教育學門  0111 教育學學類   01113 特殊教育細學類
3  01 教育領域  011 教育學門  0111 教育學學類   01114 教育行政細學類
4  01 教育領域  011 教育學門  0111 教育學學類  01115 課程與教學細學類

Processed 學門查詢 DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174 entries, 0 to 173
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   領域代碼/名稱   174 non-null    object
 1   學門代碼/名稱   174 non-null    object
 2   學類代碼/名稱   174 non-null    object
 3   細學類代碼/名稱  174 non-null    object
dtypes: object(4)
memory usage: 5.6+ KB

### 拆分薪資統計資料為博士、碩士、學士三種教育程度的資料框
接下來，我們將 `salary_multiindex_df` 根據教育程度拆分為三個獨立的資料框：碩士、學士和博士。同時，我們將扁平化多層次欄位名稱，以便於後續分析和操作。

In [20]:
import pandas as pd

# 假設 salary_multiindex_df 已從之前的步驟載入
# 如果此單元格單獨運行，請取消註釋以下行以確保 df 存在：
# file_path = '/content/薪資統計.csv'
# salary_multiindex_df = pd.read_csv(file_path, encoding='big5', header=[2, 3])

# 定義共同的識別欄位
common_identifier_cols = [
    salary_multiindex_df.columns[0],
    salary_multiindex_df.columns[1]
]

def get_degree_dataframe(df, degree_names):
    """
    根據指定的教育程度名稱，從原始 DataFrame 中提取相關欄位並扁平化 MultiIndex。
    degree_names 可以是單個字串或字串列表。
    """
    if isinstance(degree_names, str):
        degree_names = [degree_names]

    selected_cols = []
    # 首先添加共同的識別欄位
    selected_cols.extend(common_identifier_cols)

    # 添加特定教育程度的欄位
    for col_tuple in df.columns:
        if col_tuple[0] in degree_names:
            selected_cols.append(col_tuple)

    degree_df = df[selected_cols].copy()

    # 扁平化 MultiIndex 欄位名稱
    new_columns = []
    for col_tuple in degree_df.columns:
        if col_tuple[0] in [common_identifier_cols[0][0], common_identifier_cols[1][0]]:
            new_columns.append(col_tuple[0]) # 對於共同識別欄位，只保留頂層名稱
        elif pd.isna(col_tuple[1]):
             new_columns.append(col_tuple[0]) # 如果子層名稱為 NaN，則使用頂層名稱
        else:
            # 對於特定教育程度的欄位，將頂層和子層名稱合併，並清理字串
            new_columns.append(f"{col_tuple[0]}_{col_tuple[1].replace(' ', '').replace('/', '_')}")

    degree_df.columns = new_columns

    # 刪除可能因扁平化或資料結構問題而產生的空欄位
    degree_df = degree_df.dropna(axis=1, how='all')

    return degree_df

# 創建碩士學位資料框 (Master's Degree)
# 這包括頂層分類為 '碩士' 和 '碩士(日間)' 的欄位
master_degree_df = get_degree_dataframe(salary_multiindex_df, ['碩士', '碩士(日間)'])
print("\n碩士 DataFrame head:")
display(master_degree_df.head())
print("\n碩士 DataFrame info:")
master_degree_df.info()

# 創建學士學位資料框 (Bachelor's Degree)
# 這包括頂層分類為 '學士' 和 '學士(日間)' 的欄位
bachelor_degree_df = get_degree_dataframe(salary_multiindex_df, ['學士', '學士(日間)'])
print("\n學士 DataFrame head:")
display(bachelor_degree_df.head())
print("\n學士 DataFrame info:")
bachelor_degree_df.info()

# 創建博士學位資料框 (Doctorate Degree)
# 這包括頂層分類為 '博士' 的欄位
doctorate_degree_df = get_degree_dataframe(salary_multiindex_df, '博士')
print("\n博士 DataFrame head:")
display(doctorate_degree_df.head())
print("\n博士 DataFrame info:")
doctorate_degree_df.info()

碩士 DataFrame head:

       統計期     畢業年   碩士_總計 碩士(日間)_總計
0  112年 1月  109年畢業  60,601    59,016
1  112年 1月  110年畢業  59,256    57,593
2  112年 1月  111年畢業  56,018    53,035
3  112年 7月  109年畢業  62,668    61,213
4  112年 7月  110年畢業  61,391    59,907

碩士 DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   統計期        26 non-null     object
 1   畢業年        26 non-null     object
 2   碩士_總計      26 non-null     object
 3   碩士(日間)_總計  26 non-null     object
dtypes: object(4)
memory usage: 964.0+ bytes

學士 DataFrame head:

       統計期     畢業年   學士_總計 學士(日間)_總計
0  112年 1月  109年畢業  37,239    37,201
1  112年 1月  110年畢業  36,005    35,813
2  112年 1月  111年畢業  33,898    33,449
3  112年 7月  109年畢業  37,991    37,974
4  112年 7月  110年畢業  36,896    36,740

學士 DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   統計期        26 non-null     object
 1   畢業年        26 non-null     object
 2   學士_總計      26 non-null     object
 3   學士(日間)_總計  26 non-null     object
dtypes: object(4)
memory usage: 964.0+ bytes

博士 DataFrame head:

       統計期     畢業年
0  112年 1月  109年畢業
1  112年 1月  110年畢業
2  112年 1月  111年畢業
3  112年 7月  109年畢業
4  112年 7月  110年畢業

博士 DataFrame info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計期     26 non-null     object
 1   畢業年     26 non-null     object
dtypes: object(2)
memory usage: 548.0+ bytes

### 儲存拆分後的資料框為 CSV 檔案
現在，我們將這三個獨立的資料框儲存為各自的 CSV 檔案。

In [21]:
# 儲存為 CSV 檔案
master_degree_df.to_csv('/content/薪資統計_碩士.csv', index=False)
bachelor_degree_df.to_csv('/content/薪資統計_學士.csv', index=False)
doctorate_degree_df.to_csv('/content/薪資統計_博士.csv', index=False)

print("資料框已儲存為：")
print("- /content/薪資統計_碩士.csv")
print("- /content/薪資統計_學士.csv")
print("- /content/薪資統計_博士.csv")

資料框已儲存為：
- /content/薪資統計_碩士.csv
- /content/薪資統計_學士.csv
- /content/薪資統計_博士.csv